name = "gleam_parser"
version = "1.0.0"
target = "javascript"

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 0.60.0"
eyg_ir = {path = "../gleam_ir"}
eyg_interpreter = {path = "../gleam_interpreter"}
gleam_javascript = ">= 0.13.0 and < 2.0.0"
clip = ">= 1.0.0 and < 2.0.0"
argv = ">= 1.0.0 and < 2.0.0"
gleave = ">= 1.0.0 and < 2.0.0"
dag_json = ">= 1.1.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
